version: '3.8'
services:
  nlw-esports-mongo:
    build:
      dockerfile: mongo.dockerfile
      context: .
    restart: unless-stopped
    container_name: nlw-esports-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
    networks:
      - nlw-esports-network
  nlw-esports-server:
    build:
      dockerfile: node.dockerfile
      context: .
    restart: unless-stopped
    container_name: nlw-esports-node
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${WEB_PORT}:${WEB_PORT}
      - 19000:19000
      - 19001:19001
      - 19002:19002
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - WEB_PORT=${WEB_PORT}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.15.7
    volumes:
      - "${SERVER_DIR}:/www/nlw/esports/server"
      - "${WEB_DIR}:/www/nlw/esports/web"
      - "${MOBILE_DIR}:/www/nlw/esports/mobile"
    networks:
      - nlw-esports-network   
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  nlw-esports-network:
    driver: bridge